# checkout more: https://pnpm.io/catalogs
packages:
  - 'frontend'
  - 'frontend-admin'
  - 'packages/*'

catalog:
  dayjs: ^1.11.19
  react: ^19.2.1
  react-dom: ^19.2.1
  react-hook-form: ^7.66.1
  react-router: ^7.9.6
  typescript: ^5.9.3
  lucide-react: ^0.553.0
  
  '@tailwindcss/vite': ^4.1.17
  class-variance-authority: ^0.7.1
  tailwind-merge: ^3.4.0
  tailwindcss: ^4.1.17
  tw-animate-css: ^1.4.0

  '@eslint/js': ^9.39.1
  '@types/react': ^19.2.2
  '@types/react-dom': ^19.2.2
  '@types/node': ^24.10.1
  '@vitejs/plugin-react': ^5.1.0
  eslint: ^9.39.1
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-react-refresh: ^0.4.24
  globals: ^16.5.0
  vite: npm:rolldown-vite@7.2.2