# checkout more: https://pnpm.io/catalogs
packages:
  - 'frontend'

catalog:
  dayjs: ^1.11.19
  react: ^19.2.0
  react-dom: ^19.2.0
  react-hook-form: ^7.66.1
  react-router: ^7.9.6
  typescript: ^5.9.3

  '@eslint/js': ^9.39.1
  '@types/react': ^19.2.2
  '@types/react-dom': ^19.2.2
  '@types/node': ^24.10.1
  '@vitejs/plugin-react': ^5.1.0
  eslint: ^9.39.1
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-react-refresh: ^0.4.24
  globals: ^16.5.0
  vite: npm:rolldown-vite@7.2.2